### ISSUE TITLE
Token passengers undefined, tgvmax-bot deprecated ?

### ISSUE THREAD

**Issue by yohann84L** [Eywek/tgvmax-bot#24]
When adding trainline or sncf booker I always get the following error if I search for train:

```
/usr/src/src/book/trainline.ts:298
    this.token.passengers = token.passengers.filter(p => p.is_selected)
                                            ^
TypeError: Cannot read properties of undefined (reading 'filter')
    at TrainlineAuthentifier.login (/usr/src/src/book/trainline.ts:298:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TrainlineAuthentifier.getToken (/usr/src/src/book/trainline.ts:262:7)
    at TrainlineSearcher.search (/usr/src/src/book/trainline.ts:654:22)
    at Object.next (/usr/src/src/book/trainline.ts:552:21)
    at next (node:internal/streams/from:85:11)
```

I tried to run the POST request manually and I got:
```json
{
    "errors": {
        "email": [
            "Sorry! No matching account was found for this email address or password."
        ]
    }
}
```

But my email and password are correct. However, if I look to the request sent on https://www.thetrainline.com/, the url is https://www.thetrainline.com/login-service/api/login and not https://www.trainline.fr/api/v5_1 

Does this bot still work ? Or the trainline api have changed and kill this bot ?

**Comment by JulianSchl** [comment]
I am getting the same error even with a business account. Strangely I got the response once and after that the same request delivered an error 502

**Comment by MrVidipy** [comment]
Hi,
I have had the same problem since this morning.
When I go to `https://www.trainline.fr/api/v5_1/account/signin` in my browser, I have the return `{"error":"Une erreur système est survenue."}`
The bot was working fine before. Is trainline down?
