### ISSUE TITLE
Error when adding cron (frontend)

### ISSUE THREAD

**Issue by TBG-FR** [Eywek/tgvmax-bot#26]
When trying to add a `cron` through the frontend, the console shows the following error (but the cron is added)

```
vue.esm.js:1897 TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at from (<anonymous>)
    at Gu7T.e.default (vendor.fe5c74e1b9a016e6c47d.js:7:99303)
    at a.<anonymous> (app.ca14327699a7dc293e52.js:1:15313)
    at w (vendor.fe5c74e1b9a016e6c47d.js:13:9630)
    at Generator._invoke (vendor.fe5c74e1b9a016e6c47d.js:13:9418)
    at t.<computed> [as next] (vendor.fe5c74e1b9a016e6c47d.js:13:9809)
    at r (vendor.fe5c74e1b9a016e6c47d.js:13:15249)
    at vendor.fe5c74e1b9a016e6c47d.js:13:15345
```

I'm using the "latest version" (= `git clone` + `Dockerfile`)

**Comment by Eywek** [comment]
Can you provide us the network call reply?

**Comment by TBG-FR** [comment]
Yes sure !

```
HTTP/1.1 200 OK
Server: nginx/1.21.1
Date: Tue, 20 Sep 2022 13:13:13 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 447
Connection: keep-alive
X-Powered-By: Express
Access-Control-Allow-Origin: *
ETag: W/"1bf-VIpOcxcTUfM36Os7L7miOyANugk"
```

```
{"id":8,"from":"FRPAR","to":"NLAMS","minHour":null,"minMinute":null,"maxHour":null,"maxMinute":null,"cron":"0 0 * * MON","maxTravels":1,"lastTravelDate":"2022-09-26","book":false,"created_at":"2022-09-20T13:13:13.000Z","notifier":{"id":4,"name":"TBG (Num)","type":"telegram","created_at":"2022-09-20T09:46:10.000Z"},"booker":{"id":1,"name":"TBG","username":"*****@*****.fr","type":"trainline","created_at":"2022-09-20T09:30:06.000Z"}}
```
