### ISSUE TITLE
Search loading forever and then giving an error

### ISSUE THREAD

**Issue by TBG-FR** [Eywek/tgvmax-bot#28]
When trying to manually search a train journey, the search loads forever (many minutes), never displaying a result

![image](https://user-images.githubusercontent.com/18146038/191230562-8d3e2f3c-dfa8-49be-a024-10b24857c52b.png)

After many minutes, I get this error in console

```
vue.esm.js:1897 SyntaxError: Unexpected non-whitespace character after JSON at position 47
    at JSON.parse (<anonymous>)
    at a.<anonymous> (SearchJourneys.vue:215:1)
    at w (runtime.js:62:15)
    at Generator._invoke (runtime.js:296:1)
    at t.<computed> [as next] (runtime.js:114:1)
    at r (asyncToGenerator.js:17:1)
    at asyncToGenerator.js:28:1
 ```

A call on http://localhost/api/travels/journeys?from=FRLYS&to=FRTTX&date=2022-09-20&bookerId=1&untilDate=2022-10-02 or http://localhost:8080/api/travels/journeys?from=FRLYS&to=FRTTX&date=2022-09-20&bookerId=1&untilDate=2022-10-02 gives the same result, a very long loading/downloading time, and then I finally get a JSON (file) result

```
{"trips":[],"lastDate":"mar. 20 sept., 16:54"}
{"trips":[],"lastDate":"mar. 20 sept., 21:47"}
{"trips":[],"lastDate":"mer. 21 sept., 07:08"}
{"trips":[],"lastDate":"mer. 21 sept., 16:12"}
{"trips":[],"lastDate":"mer. 21 sept., 20:12"}
{"trips":[],"lastDate":"jeu. 22 sept., 07:08"}
{"trips":[],"lastDate":"jeu. 22 sept., 07:08"}
{"trips":[],"lastDate":"jeu. 22 sept., 16:54"}
{"trips":[],"lastDate":"jeu. 22 sept., 18:54"}
{"trips":[],"lastDate":"ven. 23 sept., 06:50"}
{"trips":[],"lastDate":"ven. 23 sept., 08:08"}
{"trips":[],"lastDate":"ven. 23 sept., 16:30"}
{"trips":[],"lastDate":"ven. 23 sept., 16:54"}
{"trips":[],"lastDate":"sam. 24 sept., 07:08"}
{"trips":[],"lastDate":"sam. 24 sept., 10:50"}
{"trips":[],"lastDate":"sam. 24 sept., 16:50"}
{"trips":[],"lastDate":"dim. 25 sept., 10:50"}
{"trips":[],"lastDate":"dim. 25 sept., 12:38"}
{"trips":[],"lastDate":"dim. 25 sept., 10:50"}
{"trips":[],"lastDate":"dim. 25 sept., 16:38"}
{"trips":[],"lastDate":"lun. 26 sept., 07:14"}
{"trips":[],"lastDate":"lun. 26 sept., 16:54"}
{"trips":[],"lastDate":"lun. 26 sept., 18:54"}
{"trips":[],"lastDate":"mar. 27 sept., 07:08"}
{"trips":[],"lastDate":"mar. 27 sept., 07:08"}
{"trips":[],"lastDate":"mar. 27 sept., 16:54"}
{"trips":[],"lastDate":"mar. 27 sept., 18:54"}
{"trips":[],"lastDate":"mer. 28 sept., 06:50"}
{"trips":[],"lastDate":"mer. 28 sept., 08:08"}
{"trips":[],"lastDate":"mer. 28 sept., 16:30"}
{"trips":[],"lastDate":"mer. 28 sept., 16:54"}
{"trips":[],"lastDate":"mer. 28 sept., 21:47"}
{"trips":[],"lastDate":"jeu. 29 sept., 07:08"}
{"trips":[],"lastDate":"jeu. 29 sept., 16:12"}
{"trips":[],"lastDate":"jeu. 29 sept., 20:12"}
{"trips":[],"lastDate":"ven. 30 sept., 07:08"}
{"trips":[],"lastDate":"ven. 30 sept., 07:08"}
{"trips":[],"lastDate":"ven. 30 sept., 16:54"}
{"trips":[],"lastDate":"ven. 30 sept., 18:54"}
{"trips":[],"lastDate":"sam. 1 oct., 06:38"}
{"trips":[],"lastDate":"sam. 1 oct., 16:50"}
{"trips":[],"lastDate":"sam. 1 oct., 21:47"}
{"trips":[],"lastDate":"sam. 1 oct., 21:47"}
{"trips":[],"lastDate":"dim. 2 oct., 10:50"}
{"trips":[],"lastDate":"dim. 2 oct., 17:38"}
{"trips":[],"lastDate":"lun. 3 oct., 07:14"}

```

**Comment by Eywek** [comment]
> a very long loading/downloading time

That's the expected behavior, Trainline API is quite slow, so we stream it
https://github.com/Eywek/tgvmax-bot/blob/42c5a026d12b6360406778fa793f826de14c3b30/backend/src/controllers/travel.controller.ts#L66-L85



> After many minutes

Maybe your reverse proxy is buffering the reply and not streaming it, see http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering for NGinx, I'll add it in the readme

**Comment by TBG-FR** [comment]
Oh, didn't see that part of the code, thanks !

Adding that line to NGINX did the trick, now I'm getting results displayed in the frontend 😃
